### PR TITLE
@ #43 | should add weight for provisioners

### PR DESCRIPTION
**Pull request by hieptranquoc**
connect #43 
please help me check this PR! Thank you so much!

### CODE REVIEW

**Comment by hieptranquoc** [comment]
Original data:
```
[TeracyDevCore::Config::Provisioners][WARN]: provisioners_settings: [{"_id"=>"0", "version"=>"13.1.31", "type"=>"chef_solo", "log_level"=>"info", "enabled"=>true}, {"_id"=>"2", "version"=>"13.1.31", "type"=>"chef_solo", "log_level"=>"info", "enabled"=>true, "weight"=>6}, {"_id"=>"1", "version"=>"13.1.31", "type"=>"chef_solo", "log_level"=>"info", "enabled"=>true, "weight"=>6}, {"_id"=>"3", "version"=>"13.1.31", "type"=>"chef_solo", "log_level"=>"info", "enabled"=>true, "weight"=>3}, {"_id"=>"4", "version"=>"13.1.31", "type"=>"chef_solo", "log_level"=>"info", "enabled"=>true, "weight"=>4}]
```

data after converted:
```
[TeracyDevCore::Config::Provisioners][INFO]: items: [{:_id=>"0", "version"=>"13.1.31", "type"=>"chef_solo", "log_level"=>"info", "enabled"=>true, :weight=>5}, {:_id=>"2", "version"=>"13.1.31", "type"=>"chef_solo", "log_level"=>"info", "enabled"=>true, :weight=>6}, {:_id=>"1", "version"=>"13.1.31", "type"=>"chef_solo", "log_level"=>"info", "enabled"=>true, :weight=>6}, {:_id=>"3", "version"=>"13.1.31", "type"=>"chef_solo", "log_level"=>"info", "enabled"=>true, :weight=>3}, {:_id=>"4", "version"=>"13.1.31", "type"=>"chef_solo", "log_level"=>"info", "enabled"=>true, :weight=>4}]
```

**Review by hoatle — CHANGES_REQUESTED** [review]
@hieptranquoc check my comment via PR here https://github.com/hieptranquoc/teracy-dev-core/pull/2, please review, check and merge to your working branch, and push to get this PR updated

**Comment by hoatle** [comment]
@hieptranquoc make sure to rebase to the latest develop branch

**Comment by hieptranquoc** [comment]
I've updated! Please check again!

**Review by hoatle — APPROVED** [review]
LGTM

**Pull request merged**
